### ISSUE TITLE
Code table 4.2: Wet Bulb Potential Temperature (UK)

### ISSUE THREAD

**Issue by marqh** [wmo-im/GRIB2#87] opened 2021-03-31 15:01 UTC
# Branch
https://github.com/wmo-im/GRIB2/tree/issue87

# Summary and purpose
Request for a new code table 4.2 entry for Wet Bulb Potential Temperature

# Action proposed
The Team is requested to review the proposed new parameter and approve it for implementation.

# Discussions
The UK Met Office generates data from its atmosphere models with a model diagnostic of Wet Bulb Potential Temperature, which does not appear in the current GRIB parameter code tables.  The representation this quantity within WMO GRIB2 tables would assist in the sharing of this data. 

# Finalized proposal
(edited by @jitsukoh May 28)
* Discipline: 0
* Category: 0
* Number: 32
* Name: Wet-bulb potential temperature
* Units: K

**Comment by richardweedon** [comment] 2021-04-20 07:57
[GRIB-CC-4.5-1.docx](https://github.com/wmo-im/GRIB2/files/6341656/GRIB-CC-4.5-1.docx)

**Comment by amilan17** [comment] 2021-04-20 08:02
@richardweedon  - did you close this issue on purpose?

**Comment by richardweedon** [comment] 2021-04-20 08:06
Anna

Apologies no was trying to update the attachment, must have done so by accident.

Regards

Richard

**Comment by richardweedon** [comment] 2021-04-21 10:11
Summary of changes
https://github.com/wmo-im/GRIB2/issues/87

**Comment by richardweedon** [comment] 2021-05-27 15:16
Request  the following - 
Product discipline 0 - Meteorological product  parameter category 0: temperature  32    Wet Bulb Potential Temperature  K
Product discipline 0 - Meteorological product  parameter category 0: temperature  33-191   Reserved

**Comment by jitsukoh** [comment] 2021-05-28 00:58
@richardweedon @marqh I edited the original post with the finalized proposal. Can you updated the branch accordingly?

**Comment by jitsukoh** [comment] 2021-06-16 20:58
@richardweedon @marqh I confirm that the proposal is finalized and the branch is updated. The issue is moved to the validated status.

**Closed** 2021-09-23 15:04 UTC
Labels: has branch, codeTable4.2, submitted.21-2
